### ISSUE TITLE
Adesivos de eventos

### ISSUE THREAD

**Issue by raphaelfabeni** [cerebrobr/adesivos#23]
Fala galera!
Uma questão que vou jogar no ar:
vocês acham válido adicionarmos logos de eventos, meetups e afins ou não?

**Comment by fdaciuk** [comment]
Acho massa @raphaelfabeni! Ás vezes um evento passa, e não deu pra pegar aquele adesivo legal.. se tiver aqui vai ser da hora xD

PS.: Só tem que tomar o cuidade de verificar se algum pode ter direitos autorais. Apesar de não estarmos vendendo stickers aqui, copyright é sempre um problema xD

**Comment by adammacias** [comment]
:+1:

**Comment by raphaelfabeni** [comment]
Verdade @fdaciuk ! Envolve outras coisas também como isso! Teríamos que ter um cuidado bastante rigoroso quanto a isso.
